### PR TITLE
Remove unneeded bootstrap require in app.html

### PR DESCRIPTION
**Pull request by dbarishic**
We're already including bootstrap in the main file, also the line causes a compilation error when working with Typescript and Bootstrap 4.1.1

### CODE REVIEW

**Comment by doktordirk** [comment]
while it might be unneeded, an error probably comes from the css now being in 'dist/css' and not just 'css' folder. typescript has nothing to do with that.

**Comment by croda** [comment]
Yes, a mistake on my part in the wording, was trying to be specific with the actual setup I was working with during the tutorial.

**Comment by bigopon** [comment]
Thanks @dbarishic @doktordirk we have moved the docs to the documentation repo of aurelia org https://github.com/aurelia/documentation
